#!/usr/bin/env bash
# G10 Textbook — Quiz Mode
MAX_ITERATIONS=25
COOLDOWN_SECONDS=5
MAX_CONSECUTIVE_ERRORS=10
CLAUDE_MODEL="opus"
ALLOWED_TOOLS="Read,Write,Edit,Bash,Glob,Grep,WebSearch,WebFetch"
ITERATION_TIMEOUT=2400
